# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/watercolor',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/watercolor',
                'lib_path': 'watercolor'},
  'syms': {'watercolor.core': {'watercolor.core.foo': ('core.html#foo', 'watercolor/core.py')}}}
