"""Loading simple stellar population (SSP) flux lines. Also loading the metallicity and age grids that the flux lines are computed on."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_load_sps_library.ipynb.

# %% auto 0
__all__ = ['STELLAR_LIBRARY_DIR', 'LIBRARY_FLUX_FILE', 'LIBRARY_WAVE_FILE', 'LIBRARY_AGE_FILE', 'LIBRARY_METAL_FILE',
           'load_fsps_spectral_library', 'load_fsps_age_metallicity']

# %% ../nbs/00_load_sps_library.ipynb 3
import numpy as np
import os
import matplotlib.pylab as plt
from .load_sim_stellar_catalog import Z_SOLAR_PADOVA, H0
import pkg_resources

# %% ../nbs/00_load_sps_library.ipynb 5
# _THIS_DRNAME = os.path.dirname(os.path.abspath(__file__))
# os.path.join(_THIS_DRNAME, "models", GPmodelname)

STELLAR_LIBRARY_DIR = "data/sps_library_data/"
LIBRARY_FLUX_FILE = pkg_resources.resource_stream("watercolor", STELLAR_LIBRARY_DIR + "ssp_spec_flux_lines.npy").name
LIBRARY_WAVE_FILE = pkg_resources.resource_stream("watercolor", STELLAR_LIBRARY_DIR + "ssp_spec_wave.npy").name
LIBRARY_AGE_FILE = pkg_resources.resource_stream("watercolor", STELLAR_LIBRARY_DIR + "log_age.npy").name
LIBRARY_METAL_FILE = pkg_resources.resource_stream("watercolor", STELLAR_LIBRARY_DIR + "zlegend.npy").name

# %% ../nbs/00_load_sps_library.ipynb 6
def load_fsps_spectral_library(flux_fileIn:str=LIBRARY_FLUX_FILE, # Input flux file of the stellar spectra library
                               wave_fileIn:str=LIBRARY_WAVE_FILE, # Input wavelength file of the stellar spectra library
                              ) -> tuple: #Fluxes, wavelengths 
    spec_flux = np.load(flux_fileIn)
    spec_wave = np.load(wave_fileIn)
    # print('Library shape: ', spec_flux.shape) 
    # print('Wavelength shape: ', spec_wave.shape)
    return spec_flux, spec_wave

# %% ../nbs/00_load_sps_library.ipynb 7
def _load_fsps_age(age_fileIn:str=LIBRARY_AGE_FILE # Input age file of the stellar spectra library 
                  )-> np.array: # Age in Gyr
    
    # log_age_gyr = np.load(os.path.join(dirIn, "log_age.npy")) - 9
    log_age_gyr = np.load( age_fileIn ) - 9
    age_fsps_gyr = 10**log_age_gyr
    ## (age is in 1/H0 units)
    return age_fsps_gyr

# %% ../nbs/00_load_sps_library.ipynb 8
def _load_fsps_metallicity(metal_fileIn:str=LIBRARY_METAL_FILE, # Input metallicity file of the stellar spectra library
                           Z_solar:np.float32=Z_SOLAR_PADOVA # Solar metallicity in Padova
                          ) -> np.array: #Metallicity values in Z/Z_solar units
    Z_legend = np.load( metal_fileIn )
    Z_padova_fsps = Z_legend/Z_solar
    return Z_padova_fsps

# %% ../nbs/00_load_sps_library.ipynb 9
def load_fsps_age_metallicity(age_fileIn:str=LIBRARY_AGE_FILE, # Input metallicity file of the stellar spectra library
                              metal_fileIn:str=LIBRARY_METAL_FILE, # Input age file of the stellar spectra library 
                              Z_solar:np.float32=Z_SOLAR_PADOVA # Solar metallicity in Padova
                             )-> tuple: # Age in Gyr, Metallicity in Z/Z_sun
    
    age_fsps_gyr = _load_fsps_age(age_fileIn)
    
    Z_padova = _load_fsps_metallicity(metal_fileIn, Z_solar)
    
    return age_fsps_gyr, Z_padova
