"""Importing the stellar catalogs compiled from HACC. This module may be edited for a different file reader if necessary."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_load_sim_stellar_catalog.ipynb.

# %% auto 0
__all__ = ['GALS_DIR', 'GALS_FILE', 'Z_SOLAR_HACC', 'Z_SOLAR_PADOVA', 'H0', 'load_hacc_galaxy_data', 'load_opencosmo_collection',
           'read_particles_in_a_galaxy', 'load_hacc_galaxy_data_opencosmo']

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 4
import numpy as np
import os
import matplotlib.pylab as plt
import pkg_resources
import logging
import opencosmo as oc

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 6
GALS_DIR = "data/test_hacc_stellar_catalog/"
GALS_FILE = pkg_resources.resource_stream("watercolor", GALS_DIR + "Gal_Z0.txt").name
# OPEN_COSMO_FILE = pkg_resources.resource_stream("watercolor", GALS_DIR + "haloparticles_2gpc.hdf5").name

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 7
Z_SOLAR_HACC = 0.012899 # Solar metallicity value in HACC Hydro
Z_SOLAR_PADOVA = 0.019 # Solar metallicity value in Padova 
H0 = 71.0 # Hubble Constant in HACC Hydro

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 8
def _convert_metallicity(hacc_metallicity:np.array=None, # Metallicity values from HACC  
                         Z_solar:np.float32=Z_SOLAR_PADOVA, # Z_solar value from Padova
                        )-> np.array: # Metallicity array in Z/Z_solar units
    return hacc_metallicity/Z_solar

def _convert_age(hacc_age:np.array=None, #Age in 1/H0 units 
                 H0:np.float32=H0, # LastJourney H0 value
                )-> np.array: #Age in Gyr 
    '''
    (hacc_age is in 1/H0 units)
    H0 = (71 km/s/Mpc) x (1 Mpc/3.08 x 1e19 km) = 2.37 x 1e−18 1/s
    '''
    # https://www.e-education.psu.edu/astro801/content/l10_p5.html
    
    H0_per_sec = H0*(1/(3.08*1e19)) #seconds
    one_over_H0 = 1/H0_per_sec/(3.1536*1e16)
    # age_hydro_gyr = hacc_age*one_over_H0     ### NOT SURE IF THE AGE is COSMIC (13.7 - age) or (age)

    age_hydro_gyr = one_over_H0 - hacc_age*one_over_H0  
    
    # print(age_hydro_gyr, one_over_H0)
    
    return age_hydro_gyr

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 9
def load_hacc_galaxy_data(fileIn:str=GALS_FILE, # Input galaxy catalog file from HACC hydro sim
                              Z_solar:np.float32=Z_SOLAR_PADOVA, #Solar metallicity
                              H0:np.float32=H0, # Hubble constant
                              ) -> tuple: # galaxy_tag, stellar_indices, metallicity, mass, age, x, y, z
    
    fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal, mass, age, x, y, z, vx, vy, vz = np.loadtxt(fileIn, 
                                                                 skiprows=1, 
                                                                 unpack=True)
    
    metal_z_solar = _convert_metallicity(metal, Z_solar)
    
    age_gyr = _convert_age(age, H0)
    
    return fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal_z_solar, mass, age_gyr, x, y, z, vx, vy, vz

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 10
def load_opencosmo_collection(
    particle_file_path:str = None, # Path to the OpenCosmo particle file
    catalog_file_path:str = None, # Path to the OpenCosmo catalog file
    ) -> oc.StructureCollection: # OpenCosmo particle collection


    collection = oc.open(particle_file_path,catalog_file_path).with_units("physical")
    # data = oc.open(particle_file_path).with_units("physical")
    # print(data)
    return collection

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 11
def read_particles_in_a_galaxy(
    particle_file_path: str = None, # Path to the HDF5 file containing  particle data
    catalog_file_path:str = None, # Path to the OpenCosmo catalog file
    unique_gal_tags:list = None # Unique identifier for the halo to filter particles
) -> oc.Dataset: # OpenCosmo dataset containing particles of a specific halo
    try:
        collection = load_opencosmo_collection(particle_file_path, catalog_file_path)
        # print(collection)
        
        selected_gal = collection.filter(oc.col('gal_tag').isin(unique_gal_tags))#.take(1,at='random')
        selected_star_particles = selected_gal["star_particles"]

        return selected_star_particles
    except Exception as e:
        logging.error("Failed to load halo catalog: %s", e)
        raise RuntimeError(f"Failed to load halo catalog: {e}")

# %% ../nbs/01_load_sim_stellar_catalog.ipynb 13
def load_hacc_galaxy_data_opencosmo(particle_file_path: str = None,  # Input galaxy catalog file from HACC hydro sim        
                             catalog_file_path:str = None,  # Path to the OpenCosmo catalog file                       
                             Z_solar: np.float32 = Z_SOLAR_PADOVA,  # Solar metallicity                               
                             H0: np.float32 = H0,  # Hubble constant                               
                             ) -> tuple:  # galaxy_tag, stellar_indices, metallicity, mass, age, x, y, z          
    
    # catalog = read_catalog(particle_file_path, catalog_file_path)

    collection = load_opencosmo_collection(particle_file_path, catalog_file_path)

    gal_properties = collection["galaxy_properties"]
    star_particles = collection["star_particles"]

    print('Number of available haloes in the catalog: ', np.unique(gal_properties.data["fof_halo_tag"]).size)

    ###################################
    ### below lines can be edited to keep all haloes or a random selection of haloes
    np.random.seed(42)  # For reproducibility
    num_random_halos = 200  # Number of random halos to select for testing
    selected_random_indices = np.random.randint(0, np.unique(gal_properties.data["fof_halo_tag"]).size, num_random_halos) # Randomly select 10 halos for testing
    unique_fof_halo_tags_list = np.unique(gal_properties.data["fof_halo_tag"])[selected_random_indices] # Limiting to random 10 haloes for testing
    ####################################


    print('Number of available haloes selected: ', unique_fof_halo_tags_list.size)


    # print(f" ==== Loaded catalog with {len(catalog.data)} rows and {len(catalog.data.columns)} columns. ====")
    
    # Initialize lists to collect data from all halos
    all_fof_halo_tags = []
    all_if_satellites = []
    all_gal_tags = []
    all_stellar_idx = []
    all_metals = []
    all_masses = []
    all_ages = []
    all_x = []
    all_y = []
    all_z = []
    all_vx = []
    all_vy = []
    all_vz = []
    
    for unique_fof_halo_tag in unique_fof_halo_tags_list:
        # print(f"Unique Halo Tag: {unique_fof_halo_tag}")

        selected_gal_tags = gal_properties.filter(oc.col('fof_halo_tag').isin(unique_fof_halo_tag)).data["gal_tag"].data
        # print("Selected Galaxy Tags:", selected_gal_tags)


        # Load particles for this galaxy
        star_particles = read_particles_in_a_galaxy(
            particle_file_path=particle_file_path,
            catalog_file_path=catalog_file_path,
            unique_gal_tags=selected_gal_tags)
        
        
        # Extract particle data for this halo
        x = star_particles.data['x']
        y = star_particles.data['y']
        z = star_particles.data['z']
        
        vx = star_particles.data['vx']
        vy = star_particles.data['vy']
        vz = star_particles.data['vz']
        
        fof_halo_tag = unique_fof_halo_tag*np.ones_like(x)
        mass = star_particles.data['mass']
        age = star_particles.data['age']
        metal = star_particles.data['zmet']
        stellar_idx = star_particles.data['id']
        
        if_satellite = np.ones_like(x)  # Assuming all particles are not satellites
        gal_tag = star_particles.data['gal_tag']  # Assuming no specific galaxy tag
        
        # Append data from this halo to the master arrays
        all_fof_halo_tags.append(fof_halo_tag)
        all_if_satellites.append(if_satellite)
        all_gal_tags.append(gal_tag)
        all_stellar_idx.append(stellar_idx)
        all_metals.append(metal)
        all_masses.append(mass)
        all_ages.append(age)
        all_x.append(x)
        all_y.append(y)
        all_z.append(z)
        all_vx.append(vx)
        all_vy.append(vy)
        all_vz.append(vz)
    
    # Concatenate all arrays
    fof_halo_tag = np.concatenate(all_fof_halo_tags)
    if_satellite = np.concatenate(all_if_satellites)
    gal_tag = np.concatenate(all_gal_tags)
    stellar_idx = np.concatenate(all_stellar_idx)
    metal = np.concatenate(all_metals)
    mass = np.concatenate(all_masses)
    age = np.concatenate(all_ages)
    x = np.concatenate(all_x)
    y = np.concatenate(all_y)
    z = np.concatenate(all_z)
    vx = np.concatenate(all_vx)
    vy = np.concatenate(all_vy)
    vz = np.concatenate(all_vz)
    
    # Apply conversion functions
    metal_z_solar = _convert_metallicity(metal, Z_solar)
    # age_gyr = _convert_age(age, H0) ## Not in scidac hydro sims
    age_gyr = age/1e9

    print(f"Loaded {len(x)} particles from {np.unique(gal_tag).shape[0]} galaxies in { np.unique(fof_halo_tag).shape[0] } haloes ")

    return fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal_z_solar, mass, age_gyr, x, y, z, vx, vy, vz
