"""Importing the stellar catalogs compiled from HACC. This module may be edited for a different file reader if necessary."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_load_sim_stellar_catalog.ipynb.

# %% auto #0
__all__ = ['GALS_DIR', 'GALS_FILE', 'OPEN_COSMO_FILE', 'Z_SOLAR_HACC', 'Z_SOLAR_PADOVA', 'H0', 'load_hacc_galaxy_data',
           'load_opencosmo_collection', 'read_particles_in_a_galaxy', 'load_hacc_galaxy_data_opencosmo']

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #fb514acd
import numpy as np
import os
import matplotlib.pylab as plt
import pkg_resources
import logging
import opencosmo as oc

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #96ab116c
GALS_DIR = "data/test_hacc_stellar_catalog/"
GALS_FILE = pkg_resources.resource_stream("watercolor", GALS_DIR + "Gal_Z0.txt").name

# OPEN_COSMO_FILE: path to the large HDF5 data file.
# This file is too large to bundle with the package, so we look for it
# next to the installed small data files, or fall back to None.
_opencosmo_candidate = os.path.join(os.path.dirname(GALS_FILE), "haloparticles.hdf5")
OPEN_COSMO_FILE = _opencosmo_candidate if os.path.exists(_opencosmo_candidate) else None

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #0a56a9b9
Z_SOLAR_HACC = 0.012899 # Solar metallicity value in HACC Hydro
Z_SOLAR_PADOVA = 0.019 # Solar metallicity value in Padova 
H0 = 71.0 # Hubble Constant in HACC Hydro

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #68931af7
def _convert_metallicity(hacc_metallicity:np.array=None, # Metallicity values from HACC  
                         Z_solar:np.float32=Z_SOLAR_PADOVA, # Z_solar value from Padova
                        )-> np.array: # Metallicity array in Z/Z_solar units
    return hacc_metallicity/Z_solar

def _convert_age(hacc_age:np.array=None, #Age in 1/H0 units 
                 H0:np.float32=H0, # LastJourney H0 value
                )-> np.array: #Age in Gyr 
    '''
    (hacc_age is in 1/H0 units)
    H0 = (71 km/s/Mpc) x (1 Mpc/3.08 x 1e19 km) = 2.37 x 1e−18 1/s
    '''
    # https://www.e-education.psu.edu/astro801/content/l10_p5.html
    
    H0_per_sec = H0*(1/(3.08*1e19)) #seconds
    one_over_H0 = 1/H0_per_sec/(3.1536*1e16)
    # age_hydro_gyr = hacc_age*one_over_H0     ### NOT SURE IF THE AGE is COSMIC (13.7 - age) or (age)

    age_hydro_gyr = one_over_H0 - hacc_age*one_over_H0  
    
    # print(age_hydro_gyr, one_over_H0)
    
    return age_hydro_gyr

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #80bf578e
def load_hacc_galaxy_data(fileIn:str=GALS_FILE, # Input galaxy catalog file from HACC hydro sim
                              Z_solar:np.float32=Z_SOLAR_PADOVA, #Solar metallicity
                              H0:np.float32=H0, # Hubble constant
                              ) -> tuple: # galaxy_tag, stellar_indices, metallicity, mass, age, x, y, z
    
    fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal, mass, age, x, y, z, vx, vy, vz = np.loadtxt(fileIn, 
                                                                 skiprows=1, 
                                                                 unpack=True)
    
    metal_z_solar = _convert_metallicity(metal, Z_solar)
    
    age_gyr = _convert_age(age, H0)
    
    return fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal_z_solar, mass, age_gyr, x, y, z, vx, vy, vz

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #e1d28949
def load_opencosmo_collection(
    particle_file_path:str = None, # Path to the OpenCosmo particle file
    catalog_file_path:str = None, # Path to the OpenCosmo catalog file (optional for single-file format)
    ) -> oc.StructureCollection: # OpenCosmo particle collection

    files = [f for f in [particle_file_path, catalog_file_path] if f is not None]
    collection = oc.open(*files).with_units("physical")
    return collection

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #9d443ebc
def read_particles_in_a_galaxy(
    particle_file_path: str = None, # Path to the HDF5 file containing  particle data
    catalog_file_path:str = None, # Path to the OpenCosmo catalog file
    unique_gal_tags:list = None # Unique identifier for the halo to filter particles
) -> oc.Dataset: # OpenCosmo dataset containing particles of a specific halo
    try:
        collection = load_opencosmo_collection(particle_file_path, catalog_file_path)
        # print(collection)
        
        selected_gal = collection.filter(oc.col('gal_tag').isin(unique_gal_tags))#.take(1,at='random')
        selected_star_particles = selected_gal["star_particles"]

        return selected_star_particles
    except Exception as e:
        logging.error("Failed to load halo catalog: %s", e)
        raise RuntimeError(f"Failed to load halo catalog: {e}")

# %% ../nbs/01_load_sim_stellar_catalog.ipynb #cba0062c
def load_hacc_galaxy_data_opencosmo(particle_file_path: str = None,  # Input HDF5 file (single-file or particle-only)
                             catalog_file_path: str = None,  # Optional catalog file (SciDAC 2-file format only)
                             Z_solar: np.float32 = Z_SOLAR_PADOVA,  # Solar metallicity
                             H0: np.float32 = H0,  # Hubble constant
                             num_halos: int = None,  # Max number of halos to load (None = all)
                             ) -> tuple:  # fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal_z_solar, mass, age_gyr, x, y, z, vx, vy, vz

    collection = load_opencosmo_collection(particle_file_path, catalog_file_path)

    # Detect format: new single-file has halo_properties, old SciDAC has galaxy_properties
    collection_keys = list(collection.keys()) if hasattr(collection, 'keys') else []
    has_halo_properties = "halo_properties" in collection_keys
    has_galaxy_properties = "galaxy_properties" in collection_keys

    if has_halo_properties and not has_galaxy_properties:
        # ---- New OpenCosmo single-file format ----
        star_particles = collection["star_particles"]

        fof_halo_tag = np.array(star_particles.data['fof_halo_tag'])
        unique_halo_tags = np.unique(fof_halo_tag)

        if num_halos is not None and num_halos < len(unique_halo_tags):
            np.random.seed(42)
            selected_indices = np.random.choice(len(unique_halo_tags), num_halos, replace=False)
            selected_tags = unique_halo_tags[selected_indices]
            mask = np.isin(fof_halo_tag, selected_tags)
        else:
            mask = np.ones(len(fof_halo_tag), dtype=bool)

        fof_halo_tag = fof_halo_tag[mask]
        gal_tag = fof_halo_tag.copy()  # Use fof_halo_tag as gal_tag (no separate gal_tag in new format)
        if_satellite = np.zeros_like(fof_halo_tag, dtype=np.float64)  # No satellite info in new format
        stellar_idx = np.array(star_particles.data['id'])[mask]
        metal = np.array(star_particles.data['zmet'])[mask]
        mass = np.array(star_particles.data['mass'])[mask]
        age = np.array(star_particles.data['age'])[mask]
        x = np.array(star_particles.data['x'])[mask]
        y = np.array(star_particles.data['y'])[mask]
        z = np.array(star_particles.data['z'])[mask]
        vx = np.array(star_particles.data['vx'])[mask]
        vy = np.array(star_particles.data['vy'])[mask]
        vz = np.array(star_particles.data['vz'])[mask]

        metal_z_solar = _convert_metallicity(metal, Z_solar)
        age_gyr = age  # Already in Gyr from OpenCosmo physical units

        print(f"Loaded {len(x)} star particles from {np.unique(fof_halo_tag).shape[0]} haloes (new OpenCosmo format)")

    else:
        # ---- Old SciDAC 2-file format (galaxy_properties + galaxyparticles) ----
        gal_properties = collection["galaxy_properties"]
        star_particles = collection["star_particles"]

        print('Number of available haloes in the catalog: ', np.unique(gal_properties.data["fof_halo_tag"]).size)

        unique_fof_halo_tags = np.unique(gal_properties.data["fof_halo_tag"])
        if num_halos is not None and num_halos < len(unique_fof_halo_tags):
            np.random.seed(42)
            selected_indices = np.random.choice(len(unique_fof_halo_tags), num_halos, replace=False)
            unique_fof_halo_tags_list = unique_fof_halo_tags[selected_indices]
        else:
            unique_fof_halo_tags_list = unique_fof_halo_tags

        print('Number of available haloes selected: ', unique_fof_halo_tags_list.size)

        all_fof_halo_tags = []
        all_if_satellites = []
        all_gal_tags = []
        all_stellar_idx = []
        all_metals = []
        all_masses = []
        all_ages = []
        all_x, all_y, all_z = [], [], []
        all_vx, all_vy, all_vz = [], [], []

        for unique_fof_halo_tag in unique_fof_halo_tags_list:
            selected_gal_tags = gal_properties.filter(oc.col('fof_halo_tag').isin(unique_fof_halo_tag)).data["gal_tag"].data

            star_particles_sel = read_particles_in_a_galaxy(
                particle_file_path=particle_file_path,
                catalog_file_path=catalog_file_path,
                unique_gal_tags=selected_gal_tags)

            x_ = star_particles_sel.data['x']
            y_ = star_particles_sel.data['y']
            z_ = star_particles_sel.data['z']
            vx_ = star_particles_sel.data['vx']
            vy_ = star_particles_sel.data['vy']
            vz_ = star_particles_sel.data['vz']

            all_fof_halo_tags.append(unique_fof_halo_tag * np.ones_like(x_))
            all_masses.append(star_particles_sel.data['mass'])
            all_ages.append(star_particles_sel.data['age'])
            all_metals.append(star_particles_sel.data['zmet'])
            all_stellar_idx.append(star_particles_sel.data['id'])
            all_if_satellites.append(np.ones_like(x_))
            all_gal_tags.append(star_particles_sel.data['gal_tag'])
            all_x.append(x_); all_y.append(y_); all_z.append(z_)
            all_vx.append(vx_); all_vy.append(vy_); all_vz.append(vz_)

        fof_halo_tag = np.concatenate(all_fof_halo_tags)
        if_satellite = np.concatenate(all_if_satellites)
        gal_tag = np.concatenate(all_gal_tags)
        stellar_idx = np.concatenate(all_stellar_idx)
        metal = np.concatenate(all_metals)
        mass = np.concatenate(all_masses)
        age = np.concatenate(all_ages)
        x = np.concatenate(all_x); y = np.concatenate(all_y); z = np.concatenate(all_z)
        vx = np.concatenate(all_vx); vy = np.concatenate(all_vy); vz = np.concatenate(all_vz)

        metal_z_solar = _convert_metallicity(metal, Z_solar)
        age_gyr = age / 1e9

        print(f"Loaded {len(x)} particles from {np.unique(gal_tag).shape[0]} galaxies in {np.unique(fof_halo_tag).shape[0]} haloes")

    return fof_halo_tag, if_satellite, gal_tag, stellar_idx, metal_z_solar, mass, age_gyr, x, y, z, vx, vy, vz
