name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fastai/workflows/nbdev-ci@master
        with:
          python-version: '3.12'
